---
### Supported OS version map
##
## minor versions compared using regex: '.*' - any minor
map_supported_os_version:
  x86_64:
    Linux:
      RedHat:
        '7': '.*'
        '8': '.*'
        '9': '.*'
      OracleLinux:
        '8': '.*'
        '9': '.*'
      AlmaLinux:
        '8': '.*'
        '9': '.*'
      Rocky:
        '8': '.*'
        '9': '.*'
      CentOS:
        '8': '.*'
        '9': '.*'
      Ubuntu:
        '18': '04'
        '20': '04'
        '22': '04'
      Debian:
        '9': '.*'
        '10': '.*'
        '11': '.*'
        '12': '.*'
  aarch64:
    Linux:
      Ubuntu:
        '20': '04'
        '22': '04'
