---
# temporary workaround until latest repo link added
release_version:
  '6.0':
    aarch64:
      ubuntu: '5'
    x86_64:
      ubuntu: '4'
      redhat: '4'
  '6.4':
    aarch64:
      ubuntu: '1'
    x86_64:
      ubuntu: '1'
      redhat: '1'
