galaxy_info:
  author: Zabbix Ltd
  description: Zabbix agent maintenance
  company: Zabbix Ltd

  issue_tracker_url: https://github.com/zabbix/ansible-collection/issues

  license: GPL-2.0-or-later

  min_ansible_version: '2.12'

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  
  platforms:
    - name: EL
      versions:
        - "9"
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - jammy  # 22.04
        - focal  # 20.04
        - bionic  # 18.04
    - name: Debian
      versions:
        - bullseye  # 11
        - buster  # 10
        - stretch  # 9

  galaxy_tags:
    - zabbix
    - agent
    - agentd
    - agent2
    - monitoring
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
