---
### Supported OS version map
##
## Distro -> Distro Version -> Zabbix Major -> Distro Arch
repository_map_os_support:
  RedHat:
    '7':
      '6.0': ["x86_64"]
      '6.4': ["x86_64"]
      '6.5': ["x86_64"]
    '8':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
    '9':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
  OracleLinux:
    '8':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
    '9':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
  AlmaLinux:
    '8':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
    '9':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
  Rocky:
    '8':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
    '9':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
  CentOS:
    '7':
      '6.0': ["x86_64"]
      '6.4': ["x86_64"]
      '6.5': ["x86_64"]
    '8':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
    '9':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
  Ubuntu:
    '18.04':
      '6.0': ["x86_64"]
      '6.4': ["x86_64"]
      '6.5': ["x86_64"]
    '20.04':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
    '22.04':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64", "aarch64"]
      '6.5': ["x86_64", "aarch64"]
  Debian:
    '9':
      '6.0': ["x86_64"]
      '6.4': ["x86_64"]
      '6.5': ["x86_64"]
    '10':
      '6.0': ["x86_64"]
      '6.4': ["x86_64"]
      '6.5': ["x86_64"]
    '11':
      '6.0': ["x86_64"]
      '6.4': ["x86_64"]
      '6.5': ["x86_64"]
    '12':
      '6.0': ["x86_64", "aarch64"]
      '6.4': ["x86_64"]
      '6.5': ["x86_64", "aarch64"]
  Raspbian:
    '9':
      '6.0': ["armv6l", "armv7l"]
      '6.4': ["armv6l", "armv7l"]
      '6.5': ["armv6l", "armv7l"]
    '10':
      '6.0': ["armv6l", "armv7l"]
      '6.4': ["armv6l", "armv7l"]
      '6.5': ["armv6l", "armv7l"]
    '11':
      '6.0': ["armv6l", "armv7l", "aarch64"]
      '6.4': ["armv6l", "armv7l", "aarch64"]
      '6.5': ["armv6l", "armv7l", "aarch64"]
    '12':
      '6.0': ["armv6l", "armv7l", "aarch64"]
      '6.5': ["armv6l", "armv7l", "aarch64"]
